### ISSUE TITLE
🐛 运行模板代码时报错 

### ISSUE THREAD

**Issue by fankaiLiu** [ileostar/vitesse-star#94]
#### 您使用的版本？ | Your usage version? 
当前版本
#### 您做了什么操作？ | What did you do?
 npm run dev
#### 您遇到了什么问题？ | What are your problems?
``` shell
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')     at createRouterMatcher (chunk-HSIWMAGV.js?v=82b935d5:1101:10)     at createRouter (chunk-HSIWMAGV.js?v=82b935d5:2136:19)     at createRouter (auto:20:18)     at main.ts:14:16
```
``` shell
const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
})
提示
类型“{ history: RouterHistory; }”的参数不能赋给类型“_RouterOptions”的参数。
  类型 "{ history: RouterHistory; }" 中缺少属性 "routes"，但类型 "_RouterOptions" 中需要该属性。ts(2345)
vue-router.d.ts(1244, 5): 在此处声明了 "routes"。
```
#### 您期望的结果是怎样的？ | What is your expected outcome?
正常运行

**Comment by ileostar** [comment]
感谢您提的 issue，我会尽快处理








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年6月15日(周六) 晚上11:38写道:

  

 
您使用的版本？ | Your usage version?
 
当前版本
 
您做了什么操作？ | What did you do?
 
npm run dev
 
您遇到了什么问题？ | What are your problems?
 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')     at createRouterMatcher (chunk-HSIWMAGV.js?v=82b935d5:1101:10)     at createRouter (chunk-HSIWMAGV.js?v=82b935d5:2136:19)     at createRouter (auto:20:18)     at main.ts:14:16
 const router = createRouter({   history: createWebHistory(import.meta.env.BASE_URL), }) 提示 类型“{ history: RouterHistory; }”的参数不能赋给类型“_RouterOptions”的参数。   类型 "{ history: RouterHistory; }" 中缺少属性 "routes"，但类型 "_RouterOptions" 中需要该属性。ts(2345) vue-router.d.ts(1244, 5): 在此处声明了 "routes"。
 
您期望的结果是怎样的？ | What is your expected outcome?
 
正常运行
